### ISSUE TITLE
some time it draws straight line

### ISSUE THREAD

**Issue by laxminarayan192** [amalChandran/trail-android#1]
some time it draws straight line how to solve this?

**Comment by amalChandran** [comment]
Currently working on a better version of this. Will update here shortly
once it's done. This was done as a quick POC. I'll update u.

**Comment by RameshbabuJaga** [comment]
Hi AmalChandran,
    Thanks for saving my time by giving this quick version of route draw. Now am facing the straight line issue in poly line route drawing. So kindly help me in this..

**Comment by amalChandran** [comment]
Hey Ramesh, Will fix this as soon as I find some time. Will update by end of this week.

**Comment by jivibansal** [comment]
Hi All,

The issue in the code is while using ObjectAnimator.

```
ObjectAnimator foregroundRouteAnimator = ObjectAnimator.ofObject(this,
                "routeIncreaseForward", new RouteEvaluator(), pathContainer.toArray());
foregroundRouteAnimator.setInterpolator(new AccelerateDecelerateInterpolator());
```

The object animator adds new points to the using setRouteIncreaseForward function. 
It uses RouteEvaluator to compute the middle points in between large paths. 

In case of small paths or fast animations it ends up skipping certain points of the route. To fix this you need to manually add these points in the right position.

**Comment by RameshbabuJaga** [comment]
Hi jivibansal,
 Thanks for the reply. What is right position you mean here.

**Comment by jivibansal** [comment]
Lets say that you have 7 points in your route. Now the ObjectAnimator on evaluation fetches the 0th, 3.2 and 7th point. So while adding the points in setRouteIncreaseForward() function. You need to check that if I am adding 3.2 than I need to add 1st, 2nd and 3rd point so that the final path drawn is correct.

**Comment by jivibansal** [comment]
The patch for the fix

[patch.txt](https://github.com/amalChandran/google-maps-route-animation/files/990125/patch.txt)

**Comment by ClarkXP** [comment]
@jivibansal I applied your patch, but the bug yet is triggered sometimes

**Comment by aimanabsi** [comment]
still the same bug

**Comment by ghost** [comment]
got this bug.
Scenario for these to happens?

**Comment by aimanabsi** [comment]
yeah sometimes it happens

**Comment by SandipFichadiya** [comment]
As @jivibansal stated, this is due to some LatLng(points) are being skipped. Here's the quick solution which should work.

Comment out the lines inside `setRouteIncreaseForward` function. so it should look like following
```
public void setRouteIncreaseForward(LatLng endLatLng) {
        //List<LatLng> foregroundPoints = foregroundPolyline.getPoints();
        //foregroundPoints.add(endLatLng);
        //foregroundPolyline.setPoints(foregroundPoints);
    }
```
Add the following line
`foregroundPolyline.setPoints(route);` 
above
`ObjectAnimator foregroundRouteAnimator = ObjectAnimator.ofObject(this, "routeIncreaseForward", new RouteEvaluator(), route.toArray());` line.

This should work now. `foregroundRouteAnimator` was just setting the points to`foregroundPolyline` one by one & here it was skipping some points. so we set all the points to `foregroundPolyline` manually without the help of `foregroundRouteAnimator`.

**Comment by cinohub** [comment]
I got the same issue. Anyone have a solution, please inform to me? Thank you.

**Comment by Trepapp** [comment]
Got the same issue please update the library.
Thanks in advance.

**Comment by TsaiYongChuan** [comment]
I got the same issue. Anyone have a solution, please inform to me? Thank you.
i english is so bad,sorry

**Comment by amalChandran** [comment]
@Trepapp @TsaiYongChuan @duongnv1996 @SandipFichadiya @aimanabsi 

Sorry about the delay guys. Please have a look at this update. If there is any bug, ill fix it before making it available on jCenter.
