### ISSUE TITLE
Quality Issue

### ISSUE THREAD

**Issue by mehrdad1990** [amalChandran/trail-android#10]
Hi and thanks for creating this lib.
there is a problem which I need to fix....when you zoom in too much you'll see the quality of the line decreases since that is a view and it is scaling...but this is not the case in Uber.
how can we fix this issue?
and there is also flickering issue when trying to draw the line in the beginning of the animation...

any help would be appreciated

**Comment by amalChandran** [comment]
You are right about the scaling part, it has to be implemented in a different way. Right now, the route and the markers are drawn on a view and that view is scaled based on the maps zoom level in sync. 

The flickering issue is something that happens because the multiple animators used here are not in sync.  If you manage to fix it, do sent a pull request. It is taking me longer to finish the rewrite. I cannot give any timeline as of now.

**Comment by mehrdad1990** [comment]
thanks for your answer ... any clues for raising the quality issue ?

**Comment by praba1989** [comment]
Hi @mehrdad1990  I'm just set routeWidth is 10. it's works for me in all zoom level

**Comment by mehrdad1990** [comment]
@praba1989 you sure about that ?
